/**
 * LLM Wiki core: schema seeding, ingest orchestration, index/log management.
 *
 * Wiki lives at VAULT_DIR/Wiki/ with:
 *   SCHEMA.md   — conventions for generated pages
 *   index.md    — catalog of all wiki pages
 *   log.md      — append-only ingest history
 *   *.md        — generated wiki pages
 */

import { promises as fs } from 'node:fs'
import path from 'node:path'

/* ─── Types ─── */

export interface WikiPage {
  name: string        // page title (also file stem)
  file: string        // relative path inside Wiki/
  summary: string     // one-line summary from index
  sourceCount: number // how many source ingests contributed
  createdAt: string   // ISO date string
}

export interface WikiLogEntry {
  timestamp: string
  sourcePath: string
  pagesCreated: string[]
  pagesUpdated: string[]
}

/* ─── Constants ─── */

const SCHEMA_CONTENT = `# Wiki Schema

## Conventions
1. One concept per page. Filename = concept name in PascalCase (spaces replaced with dashes).
2. First line is a level-1 heading matching the concept name.
3. Link to other wiki pages using Obsidian wikilinks: [[Page Name]].
4. Each page should have these sections:
   - ## Summary — 2-3 sentence overview
   - ## Details — expanded explanation
   - ## Related — list of wikilinks to related pages
5. Pages are generated by Ollama from source documents. Do not edit generated pages.
6. Source documents are immutable — the wiki is a derived layer.
`

/* ─── Helpers ─── */

function wikiDir(vaultDir: string): string {
  return path.join(vaultDir, 'Wiki')
}

function sanitizeFileName(name: string): string {
  return name
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, '-')
    .substring(0, 100)
}

/**
 * Validate that a source path is inside VAULT_DIR or PROJECTS_DIR.
 */
export function validateSourcePath(
  sourcePath: string,
  vaultDir: string,
  projectsDir: string
): boolean {
  const resolved = path.resolve(sourcePath)
  const resolvedVault = path.resolve(vaultDir)
  const resolvedProjects = path.resolve(projectsDir)
  return (
    (resolved.startsWith(resolvedVault + path.sep) || resolved === resolvedVault) ||
    (resolved.startsWith(resolvedProjects + path.sep) || resolved === resolvedProjects)
  )
}

/* ─── Schema ─── */

/**
 * Ensure Wiki/ directory and SCHEMA.md exist.
 * Creates them on first call; is a no-op subsequently.
 */
export async function ensureWikiDir(vaultDir: string): Promise<string> {
  const dir = wikiDir(vaultDir)
  await fs.mkdir(dir, { recursive: true })

  const schemaPath = path.join(dir, 'SCHEMA.md')
  try {
    await fs.access(schemaPath)
  } catch {
    await fs.writeFile(schemaPath, SCHEMA_CONTENT, 'utf-8')
  }

  return dir
}

/* ─── Index ─── */

/**
 * Parse Wiki/index.md into an array of WikiPage objects.
 */
export async function parseIndex(vaultDir: string): Promise<WikiPage[]> {
  const indexPath = path.join(wikiDir(vaultDir), 'index.md')

  try {
    await fs.access(indexPath)
  } catch {
    return []
  }

  const content = await fs.readFile(indexPath, 'utf-8')
  const lines = content.split('\n')
  const pages: WikiPage[] = []

  for (const line of lines) {
    // Format: - [[Page Name]] — Summary (sources: N, created: YYYY-MM-DD)
    const match = line.match(/^-\s+\[\[(.+?)\]\]\s+—\s+(.+?)\s+\(sources:\s*(\d+),\s*created:\s*(\d{4}-\d{2}-\d{2})\)$/)
    if (match) {
      pages.push({
        name: match[1],
        file: `${sanitizeFileName(match[1])}.md`,
        summary: match[2],
        sourceCount: parseInt(match[3], 10),
        createdAt: match[4],
      })
    }
  }

  return pages
}

/**
 * Rewrite index.md from scratch given the pages array.
 */
async function writeIndex(vaultDir: string, pages: WikiPage[]): Promise<void> {
  const indexPath = path.join(wikiDir(vaultDir), 'index.md')

  const lines = ['# Wiki Index', '']
  for (const page of pages.sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`- [[${page.name}]] — ${page.summary} (sources: ${page.sourceCount}, created: ${page.createdAt})`)
  }
  lines.push('')

  await fs.writeFile(indexPath, lines.join('\n'), 'utf-8')
}

/* ─── Log ─── */

/**
 * Append an entry to Wiki/log.md.
 */
async function appendLog(vaultDir: string, entry: WikiLogEntry): Promise<void> {
  const logPath = path.join(wikiDir(vaultDir), 'log.md')

  // Create header if file doesn't exist
  try {
    await fs.access(logPath)
  } catch {
    await fs.writeFile(logPath, '# Wiki Log\n\n', 'utf-8')
  }

  const lines = [
    `## ${entry.timestamp}`,
    `- Source: \`${entry.sourcePath}\``,
  ]

  if (entry.pagesCreated.length > 0) {
    lines.push(`- Created: ${entry.pagesCreated.map(p => `[[${p}]]`).join(', ')}`)
  }
  if (entry.pagesUpdated.length > 0) {
    lines.push(`- Updated: ${entry.pagesUpdated.map(p => `[[${p}]]`).join(', ')}`)
  }
  lines.push('')

  await fs.appendFile(logPath, lines.join('\n') + '\n', 'utf-8')
}

/* ─── Ingest ─── */

/**
 * Ingest a source file into the wiki.
 * Reads the file, sends to Ollama for concept extraction, creates/updates wiki pages.
 */
export async function ingestSource(
  vaultDir: string,
  projectsDir: string,
  sourcePath: string
): Promise<{ pagesCreated: string[]; pagesUpdated: string[] }> {
  // Validate source path
  if (!validateSourcePath(sourcePath, vaultDir, projectsDir)) {
    throw new Error('Source path must be inside VAULT_DIR or PROJECTS_DIR')
  }

  // Ensure wiki directory exists
  const dir = await ensureWikiDir(vaultDir)

  // Read source file
  const content = await fs.readFile(sourcePath, 'utf-8')
  const truncated = content.slice(0, 4000)

  // Ask Ollama to extract concepts
  const prompt = `You are a knowledge wiki builder. Given the following source document, extract 1-3 key concepts worth having their own wiki page.

For each concept, output EXACTLY this format (one concept per line):
CONCEPT: <name> | SUMMARY: <one-line summary> | CONTENT: <2-3 paragraph explanation>

Use Obsidian wikilinks [[Like This]] to reference other concepts you mention.

Source document:
${truncated}

Concepts:`

  // We reuse the Ollama generate function via summarizeProject with a custom prompt
  // Since summarizeProject uses a specific prompt, we need to call Ollama directly
  const ollamaUrl = process.env.OLLAMA_URL || 'http://localhost:11434'
  const ollamaModel = process.env.OLLAMA_MODEL || 'llama3.1:8b'

  let responseText: string

  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 60000)

    const response = await fetch(`${ollamaUrl}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: ollamaModel,
        prompt,
        stream: false,
      }),
      signal: controller.signal,
    })

    clearTimeout(timeout)

    if (!response.ok) {
      throw new Error(`Ollama API error: ${response.status}`)
    }

    const data = await response.json()
    responseText = data.response || ''
  } catch (error) {
    if (error instanceof Error && error.message.includes('Ollama API error')) {
      throw error
    }
    // Ollama unavailable — return empty
    return { pagesCreated: [], pagesUpdated: [] }
  }

  // Parse Ollama response
  const concepts = parseConcepts(responseText)

  if (concepts.length === 0) {
    return { pagesCreated: [], pagesUpdated: [] }
  }

  // Load existing index
  const existingPages = await parseIndex(vaultDir)
  const existingMap = new Map(existingPages.map(p => [p.name, p]))

  const pagesCreated: string[] = []
  const pagesUpdated: string[] = []

  for (const concept of concepts) {
    const fileName = sanitizeFileName(concept.name) + '.md'
    const filePath = path.join(dir, fileName)

    const pageContent = [
      `# ${concept.name}`,
      '',
      '## Summary',
      concept.summary,
      '',
      '## Details',
      concept.content,
      '',
      '## Related',
      extractWikiLinks(concept.content).map(link => `- [[${link}]]`).join('\n') || '- (none yet)',
      '',
    ].join('\n')

    const existing = existingMap.get(concept.name)

    if (existing) {
      // Update existing page
      await fs.writeFile(filePath, pageContent, 'utf-8')
      existing.sourceCount += 1
      existing.summary = concept.summary
      pagesUpdated.push(concept.name)
    } else {
      // Create new page
      await fs.writeFile(filePath, pageContent, 'utf-8')
      const today = new Date().toISOString().split('T')[0]
      existingPages.push({
        name: concept.name,
        file: fileName,
        summary: concept.summary,
        sourceCount: 1,
        createdAt: today,
      })
      pagesCreated.push(concept.name)
    }
  }

  // Write updated index
  await writeIndex(vaultDir, existingPages)

  // Append to log
  await appendLog(vaultDir, {
    timestamp: new Date().toISOString(),
    sourcePath: path.relative(vaultDir, sourcePath) || sourcePath,
    pagesCreated,
    pagesUpdated,
  })

  return { pagesCreated, pagesUpdated }
}

/* ─── Parsing Utilities ─── */

interface ParsedConcept {
  name: string
  summary: string
  content: string
}

/**
 * Parse CONCEPT lines from Ollama response.
 */
export function parseConcepts(text: string): ParsedConcept[] {
  const concepts: ParsedConcept[] = []
  const lines = text.split('\n')

  for (const line of lines) {
    const match = line.match(/CONCEPT:\s*(.+?)\s*\|\s*SUMMARY:\s*(.+?)\s*\|\s*CONTENT:\s*(.+)/)
    if (match) {
      concepts.push({
        name: match[1].trim(),
        summary: match[2].trim(),
        content: match[3].trim(),
      })
    }
  }

  return concepts
}

/**
 * Extract [[wikilink]] targets from text.
 */
export function extractWikiLinks(text: string): string[] {
  const links: string[] = []
  const regex = /\[\[(.+?)\]\]/g
  let match
  while ((match = regex.exec(text)) !== null) {
    if (!links.includes(match[1])) {
      links.push(match[1])
    }
  }
  return links
}

/* ─── List Pages ─── */

/**
 * List all .md pages in Wiki/ (excluding index, log, schema).
 */
export async function listWikiPages(vaultDir: string): Promise<WikiPage[]> {
  const dir = wikiDir(vaultDir)

  try {
    await fs.access(dir)
  } catch {
    return []
  }

  const index = await parseIndex(vaultDir)

  // If index is empty, scan files directly
  if (index.length === 0) {
    const entries = await fs.readdir(dir)
    const skipFiles = new Set(['index.md', 'log.md', 'SCHEMA.md'])
    const pages: WikiPage[] = []

    for (const entry of entries) {
      if (!entry.endsWith('.md') || skipFiles.has(entry)) continue
      const stat = await fs.stat(path.join(dir, entry))
      pages.push({
        name: entry.replace(/\.md$/, '').replace(/-/g, ' '),
        file: entry,
        summary: '',
        sourceCount: 0,
        createdAt: stat.birthtime.toISOString().split('T')[0],
      })
    }
    return pages
  }

  return index
}
